### ISSUE TITLE
The meta.refinery.local_hostname field, is not set properly

### ISSUE THREAD

**Issue by puckpuck** [honeycombio/refinery#385]
**Versions**

- Go:
- Refinery: 1.8.1

**Steps to reproduce**

1. Setup a multi-node cluster
2. Set the `AddHostMetadataToTrace` config property to true
3. query filtered on a single trace, grouped by `meta.refinery.local_hostname` and notice a trace will have multiple hosts used when it should only be 1 

**Additional context**

After further digging into the code, this is set at the Libhoney client level, which is used for both peer communication and to send to honeycomb. It seems the peer that receives the span initially is what the hostname will be set to.

**Comment by bdarfler** [comment]
Since I did some code digging I'll put a few notes here.

Refinery [sets](https://github.com/honeycombio/refinery/blob/f44521f69b2fe939c07309b794477adbb7382730/transmit/transmit.go#L58-L63) the `meta.refinery.local_hostname` on its underlying libhoney client. 

That is [done](https://github.com/honeycombio/refinery/blob/f44521f69b2fe939c07309b794477adbb7382730/cmd/refinery/main.go#L165-L166) on both the peer and the upstream `Transmissions`.

What I'm not clear on is what does Libhoney do when there is an attribute name collision where the event already has an attribute of the same name that the Libhoney client is trying to set.

**Comment by puckpuck** [comment]
It probably makes better sense to add the hostname field here just before sending it to Honeycomb, as we do for the dry run field. https://github.com/honeycombio/refinery/blob/main/collect/collect.go#L462-L474
