### ISSUE TITLE
Improve SendTicker documentation

### ISSUE THREAD

**Issue by mterhar** [honeycombio/refinery#546]
The current documentation for SendTicker says:

> A short timer that determines the duration to use to check for traces to send.

The configuration reference says: 

> SendTicker is a short timer; it determines the duration to use to check for traces to send

Neither of those are wrong, but they don't state why you'd want it to be higher or lower or what the impact of that change is. 

### One example

A deployment was having `incoming channel` overruns where too many spans would hit the incoming channel to be processed. Since the incoming channel is set to 3x the cache capacity, they turned the cache capacity up from 140,000 to 210,000 and it had no impact. At 140,000, this deployment had no collect cache overruns and the sent trace cache was fine so it didn't seem like increasing the cache capacity anymore was going to help.

If it's not the amount of storage, the next thing to look at was how often it was processing the things in the channel. The first idea was to "check the channels more often" so SendTicker looked promising. The first assumption was that it was a control loop pacer so the lower its setting, the more often the incoming channels would be cleared. 

When we set SendTicker to 50 ms (half of the default value), the incoming channel overruns got worse. When we checked the code, the SendTicker is actually the mechanism that takes the collect loop away from incoming channels and spends time on the InMemCache to review the traces and send any that have reached timeout. 

After realizing this, we set the SendTicker to 200ms (double the default value) so more time is spent emptying to incoming channels and it entirely resolved the spikes. The CollectCache size was still big enough that it didn't overrun and all was well. 

### Suggestion

Add something to the docs like: 

> A short timer that determines the duration between trace cache review runs to send.
> Increasing this will spend more time processing incoming events to reduce `incoming-` or `peer_router_dropped` spikes
> Decreasing this will check the trace cache for timeouts more frequently.

**Comment by kentquirk** [comment]
@mterhar This is an interesting one; if data arrives at the channel faster than it can be processed, the depth of the channel makes no difference since it will eventually overflow. This system is apparently sized right at its processing limits, and increasing SendTicker gave you just enough additional headroom to handle it. 

I may reword this a bit to add that extra detail, but I think it's also a candidate for a new Rule of Thumb: if your `collector_incoming_queue` size doesn't approach zero fairly often, you probably are running at the hairy edge of the capabilities of your cluster and a burst of high traffic will likely start overrunning queues. 

Thanks for the note.

**Comment by mterhar** [comment]
Sorry to come back to this late but I wanted to clarify one thing. The cluster was sitting at 20-30% most of the time but occasional batch jobs would run that blasted spans out at 1000x the normal rate. This change allowed the cluster to handle those without moving the average usage down to 10%.

**Comment by kentquirk** [comment]
Fixed in v2.0.
