### ISSUE TITLE
"AddSpanCountToRoot" field reports wrong span count due to including span annotations

### ISSUE THREAD

**Issue by seh** [honeycombio/refinery#555]
# Versions

- **Go:** 1.19.3
- **Refinery:** [1.18.0](https://github.com/honeycombio/refinery/releases/tag/v1.18.0)

# Steps to reproduce

1. In the Refinery configuration, set the new "AddSpanCountToRoot" field (as of #532) to true.
1. Publish several traces that flow through Refinery to Honeycomb, including at least one span event on some of the trace spans.
1. Inspect the root span of one of these traces in a Honeycomb query.
1. Observe that the "meta.span_count" field is present on the root span and populated with a positive integer.
1. Observe that the "meta.span_count" field's count is greater than the number of spans in the trace, and is instead the sum of the trace count and the span event count.

# Additional context

[I reported this problem first in the "discuss-refinery" channel](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1667833743521379) of the "Honeycomb Pollinators" Slack workspace.

In [file _types/events.go_'s `(*types.Trace).SpanCount` method](https://github.com/honeycombio/refinery/blob/a72e763b59fb5eccbab9235f16d487c39dcd586f/types/event.go#L71-L74), the current implementation reports the length of the "spans" field's slice:
```go
// SpanCount gets the number of spans currently in this trace as int64
func (t *Trace) SpanCount() int64 {
	return int64(len(t.spans))
}
```
A slower but more accurate way to report this count is as follows:
```go
// SpanCount reports the count of spans currently in this trace.
func (t *Trace) SpanCount() int64 {
	var count int64
	for _, s := range t.spans {
		if annoType, ok := s.data["meta.annotation_type"]; !ok || annoType != "span_event" {
			count++
		}
	}
	return count
}
```
Alternately, if you don't mind using the zero value returned for a key that's not present in the map:
```go
// SpanCount reports the count of spans currently in this trace.
func (t *Trace) SpanCount() int64 {
	var count int64
	for _, s := range t.spans {
		if s.data["meta.annotation_type"] != "span_event" {
			count++
		}
	}
	return count
}
```
Are there other annotation types that we need to omit? Perhaps "link?"

**Comment by kentquirk** [comment]
@seh thanks for the issue and the code. 

The main driver of this feature was to annotate traces with span counts in a way that Refinery's rules could evaluate them, so that someone could, for example, use a higher sample rate on "large" traces. If we exclude span events from that, it actually breaks that particular use case.

Because of this, the fix is a little more subtle than you've outlined here, and I need to do a bit of work and testing to minimize its impact and do it in a backwards-compatible way. So it's in progress, but will be a while before a fix appears.

**Comment by kentquirk** [comment]
Further discussion in [this thread on Pollinators](https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1678144455948289?thread_ts=1678137412.788079&cid=C4T3A32CX).

**Comment by kentquirk** [comment]
As noted above, our existing meta value is badly named. We call it `meta.span_count` but it's actually the count of all the children of the root, including spans and span events. 

We should actually have several values:
* `meta.spanevent_count` -- the number of span events on the trace
* `meta.spanlink_count` -- the number of span links on the trace
* `meta.span_count` -- the number of spans on the trace
* `meta.event_count` -- the number of honeycomb events on the trace (the sum of the 3 preceding values)

In order to do this, we need to allow old configurations to continue to use `meta.span_count` and to opt into the new names.

There are 2 ways to do this that I've thought of:
* Bump the config file version number and add individual config values for each of these fields; if version is 2, then we use the old definition, but in version 3 we interpret the new way.
* Add a new, single config value called `AddSpanCountsToRoot`, with validation allowing only one of the two to be used, and if the plural form is used we use the new definitions. This wouldn't have individual control over all these values, but I don't think that matters very much.

Personally I prefer the second option, but I'd love to hear other thoughts.

**Comment by fujin** [comment]
I like the second option except for that it took me multiple re-readings to notice which plural form (`Counts`) you were referring to! Is there a more intention revealing name?

**Comment by seh** [comment]
I am partial to the first option, wherein there would be a new struct field that offered individual options for adding any of the four counts, all defaulting to omitting them. That way, if I only care about one of the counts, I won't wind up with all four just to get that one.

**Comment by kentquirk** [comment]
We're leaning  toward the second option right now, so that we can do it in a backwards-compatible way.

**Comment by VinozzZ** [comment]
To better differentiate between the new config and the existing `AddSpanCountToRoot`, we are thinking to use `AddCountsToRoot` as the new config name

**Comment by VinozzZ** [comment]
Since enabling `AddCountsToRoot` will essentially overwrite `AddSpanCountToRoot`, we have decided to NOT add validation logic in the config layer to make sure only one of these two configs are set.  Instead, whenever `AddCountsToRoot` is set to true, Refinery will just ignore `AddSpanCountToRoot`.
