### ISSUE TITLE
Warn or error on known bad rules configuration

### ISSUE THREAD

**Issue by cartermp** [honeycombio/refinery#566]
Similar to https://github.com/honeycombio/refinery/issues/559, but tracking separately...

Today, if you have a typo in rules config like `Sample` instead of `Sampler`, refinery will just sample all traces. That can lead to way more event volume than desired until it's fixed.

Ideally, if there's a known bad configuration like this, we could either warn or error on it.

**Comment by kentquirk** [comment]
I've done some investigation, and it seems like the right answer here is to leverage jsonschema, since YAML and TOML are freely convertible to and from JSON -- at least at the level we use in Refinery config.

I also think it's probably best done as a separate tool that someone can run separately, rather than embedding it into the refinery executable. (Although I'd hear arguments to the contrary!)

Writing the schema is not technically difficult, but is a bit tedious so is expected to take several days of work. It's now on the list of things to do soon-ish.

**Comment by seh** [comment]
I maintain a schema in CUE that could be used for validation as well, if you'd like to see it. It's focused more on code generation than validation, as it's imbibed with the default values used by the Refinery application.
