### ISSUE TITLE
Dropping sampled traces shouldn't be logged at info level 

### ISSUE THREAD

**Issue by drew-eero** [honeycombio/refinery#839]
**Is your feature request related to a problem? Please describe.**

Yes, we're down sampling quite a few traces and noticed that the service is logging at info level each time a trace is dropped. This is putting a lot of excess load on our logging infrastructure. (We're going to ignore logs from refinery for now since they're just too high volume) 

Some of the logs 
```
time="2023-08-16T21:01:42Z" level=info msg="Dropping trace because of sampling" dataset=prod-traces reason="rules/trace/Dynamically Sample 2XX Responses:emadynamic/diagnostics•," trace_id=dc96b153cf110c0d
time="2023-08-16T21:01:42Z" level=info msg="Dropping trace because of sampling" dataset=prod-traces reason="rules/trace/Down Sample Node" trace_id=9a89afce1ea5c9f5
time="2023-08-16T21:01:42Z" level=info msg="Dropping trace because of sampling" dataset=prod-traces reason="rules/trace/Dynamically Sample 2XX Responses:emadynamic/diagnostics•," trace_id=bf78a5ef83290c6f
time="2023-08-16T21:01:42Z" level=info msg="Dropping trace because of sampling" dataset=prod-traces reason="rules/trace/Dynamically Sample 2XX Responses:emadynamic/diagnostics•," trace_id=52bbf7983cd4f139

```

**Describe the solution you'd like**

Log dropped traces at the debug level so they're still accessible, but make info log level a bit more manageable. This would give us the needed information for troubleshooting sampling issues, but also reduce the load on our logging infrastructure.   

**Describe alternatives you've considered**

Just ignoring all logs from refinery (we're currently doing this)

**Additional context**

We're running 

```
ARG REFINERY_VERSION=1.19.0
```

**Comment by kentquirk** [comment]
FWIW, we readjusted log levels in v2.0 so that there are more choices about what you see and don't see. We now recommend that most teams operate on Warn -- the message you note is still Info, but a lot of the other noise has been moved to Debug.

There have been a lot of really meaningful changes since 1.19, and most customers (including some very large ones) have been very happy with the upgrades. I'd recommend upgrading to 2.1 whenever you can find the time.

I'm going to close this issue for now, but if you do upgrade and still think it's a problem, please reopen or make a new one.
