### ISSUE TITLE
Allow rules and keys to specify some level of span context (particularly root span)

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#906]
**Is your feature request related to a problem? Please describe.**
Multiple customers ([one example](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1700673134994119)) have requested the ability to specify keys or rules that are restricted to a subset of possible spans. 

**Describe the solution you'd like**
Perhaps being able to specify something like `root.column_name` is enough to solve most use cases.

**Describe alternatives you've considered**
OTTL, or a more elaborate conditional structure.

**Additional context**

**Comment by VinozzZ** [comment]
related to #646

**Comment by fchikwekwe** [comment]
This issue will technically be solved when #981 merges, but the change is not optimal. Right now, we check root span context for every span in a trace, but since all spans share a root span we only need to do this once. @kentquirk suggested that we add a flag to `extractValueFromSpan` to see if the root span for that trace has already been checked.

**Comment by kentquirk** [comment]
Closed by #1018
