### ISSUE TITLE
Prometheus metrics documentation

### ISSUE THREAD

**Issue by reynico** [honeycombio/refinery#943]
hey there! I haven't found documentation about the exposed Prometheus metrics so here's the deal: I understand that `trace_accepted` is the counter for the amount of traces that were accepted by the server, and  `trace_span_count_count` is the amount of traces (all of them, accepted or not).

Sometimes we found that `trace_span_count_count` is greater than `trace_accepted`, thus the graph render is a bit weird.

<img width="1378" alt="image" src="https://github.com/honeycombio/refinery/assets/715768/0e7b1ba2-785a-4465-b0dd-785e051619a5">

Am I missing something?

**Comment by kentquirk** [comment]
`trace_accepted` is a **counter** incremented whenever a new trace ID is received by refinery. So it's basically a record of the number of traces refinery sees on its input.

`trace_span_count` is a **histogram** of the number of descendants in a trace -- it's tracking the size of traces in terms of the number of spans (and other children, like span events) that they contain. So `trace_span_count_count` is the number of points that were recorded in that histogram during the most recent period. You'd normally not ever look at it except when calculating an average.

Basically, the two values are effectively completely unrelated.

If you're trying to see the number of traces accepted, kept, and dropped, then the stats you want are `trace_accepted`, `trace_send_kept`, and `trace_send_dropped`.

These tell you about the behavior based on memory usage and timeouts:

```go
	TraceSendGotRoot        = "trace_send_got_root"
	TraceSendExpired        = "trace_send_expired"
	TraceSendEjectedFull    = "trace_send_ejected_full"
	TraceSendEjectedMemsize = "trace_send_ejected_memsize"
	TraceSendLateSpan       = "trace_send_late_span"
```

GotRoot tells you about traces that received a root span before timeout, while Expired are the ones that timed out. The ejected stats tell you what happens when you haven't given refinery enough memory or timeouts are too long -- Full means that its trace cache ran out of trace space before memory ran out, and Memsize tells you that memory was too small to contain your cache. LateSpan means that a span arrived after the trace decision was made.

Hope that helps!

**Comment by reynico** [comment]
awesome, thank you Kent!
